<Project>
  <PropertyGroup>
    <Version>0.25</Version>

    <SideScrollVersion>0.25</SideScrollVersion>
    <AvaloniaVersion>11.3.18</AvaloniaVersion>
    <AvaloniaEditVersion>11.4.1</AvaloniaEditVersion>

    <TargetFramework>net8.0</TargetFramework>
    <Configurations>Debug;Release;DebugX86</Configurations>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
</Project>
