<Project>
  <PropertyGroup>
    <Version>0.9.9</Version>

    <SideScrollVersion>0.9.9</SideScrollVersion>
    <AvaloniaVersion>11.3.0</AvaloniaVersion>
    <AvaloniaEditVersion>11.3.0</AvaloniaEditVersion>

    <TargetFramework>net8.0</TargetFramework>
    <Configurations>Debug;Release;DebugX86</Configurations>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
</Project>
