<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="App.xaml" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="App.xaml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Themes.Fluent" Version="$(AvaloniaVersion)" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="$(AvaloniaVersion)" />
    <PackageReference Include="SideScroll.Avalonia.Charts.LiveCharts" Version="$(SideScrollVersion)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\VideoGamesDB.Tabs\VideoGamesDB.Tabs.csproj" />
  </ItemGroup>

</Project>
