<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <EnableDefaultCompileItems>False</EnableDefaultCompileItems>
    <ApplicationIcon />
    <StartupObject />
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="**\*.cs" Exclude="obj\**;App.xaml.cs;MainWindow.cs;Assets\Icons.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Desktop" Version="$(AvaloniaVersion)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Libraries\VideoGamesDB.Avalonia\VideoGamesDB.Avalonia.csproj" />
  </ItemGroup>

</Project>
